// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azaetpomvpcydytcedwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6YWV0cG9tdnBjeWR5dGNlZHdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MDEwNDksImV4cCI6MjA3MzQ3NzA0OX0.mCj4ofWFei3c6Ldm1A8BfKuMYACRvGyJOlUBlV0Q5Mc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});